### ISSUE TITLE
Overlapping text

### ISSUE THREAD

**Issue by miclill** [jmforsythe/Git-Heat-Map#4]
There is a lot of overlapping text for the repo I tried. Also I wondered why there are no colors?

![image](https://user-images.githubusercontent.com/4736527/215328070-e8e370c8-507a-4c69-b1bb-5f3bed494ef9.png)

repo tried: https://github.com/tokiwa-software/fuzion

**Comment by jmforsythe** [comment]
Currently the overlapping text is intented, the white outline on the text should help you to read the top most layer.
To get the colours, put an email in to the box at the bottom and press submit. A % acts as a wildcard, so typing alice% should highlight files edited by any email starting with alice.
